/**
 * @fileoverview gRPC-Web generated client stub for sdmrpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.0
// source: sdm.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var base_pb = require('./base_pb.js')
const proto = {};
proto.sdmrpc = require('./sdm_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sdmrpc.HelloClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sdmrpc.HelloPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.HelloRequest,
 *   !proto.sdmrpc.HelloResponse>}
 */
const methodDescriptor_Hello_SayHello = new grpc.web.MethodDescriptor(
  '/sdmrpc.Hello/SayHello',
  grpc.web.MethodType.UNARY,
  base_pb.HelloRequest,
  base_pb.HelloResponse,
  /**
   * @param {!proto.sdmrpc.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  base_pb.HelloResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.HelloResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.HelloResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.HelloClient.prototype.sayHello =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Hello/SayHello',
      request,
      metadata || {},
      methodDescriptor_Hello_SayHello,
      callback);
};


/**
 * @param {!proto.sdmrpc.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.HelloResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.HelloPromiseClient.prototype.sayHello =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Hello/SayHello',
      request,
      metadata || {},
      methodDescriptor_Hello_SayHello);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sdmrpc.CoreClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sdmrpc.CorePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.StartRequest,
 *   !proto.sdmrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_Start = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/Start',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.StartRequest,
  proto.sdmrpc.CoreInfoResponse,
  /**
   * @param {!proto.sdmrpc.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.start =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/Start',
      request,
      metadata || {},
      methodDescriptor_Core_Start,
      callback);
};


/**
 * @param {!proto.sdmrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.start =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/Start',
      request,
      metadata || {},
      methodDescriptor_Core_Start);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_CoreInfoListener = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/CoreInfoListener',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.sdmrpc.CoreInfoResponse,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.CoreInfoResponse>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.coreInfoListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/CoreInfoListener',
      request,
      metadata || {},
      methodDescriptor_Core_CoreInfoListener);
};


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.CoreInfoResponse>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CorePromiseClient.prototype.coreInfoListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/CoreInfoListener',
      request,
      metadata || {},
      methodDescriptor_Core_CoreInfoListener);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.OutboundGroupList>}
 */
const methodDescriptor_Core_OutboundsInfo = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/OutboundsInfo',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.sdmrpc.OutboundGroupList,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.OutboundGroupList.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.outboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/OutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_OutboundsInfo);
};


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CorePromiseClient.prototype.outboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/OutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_OutboundsInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.OutboundGroupList>}
 */
const methodDescriptor_Core_MainOutboundsInfo = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/MainOutboundsInfo',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.sdmrpc.OutboundGroupList,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.OutboundGroupList.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.mainOutboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/MainOutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_MainOutboundsInfo);
};


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.OutboundGroupList>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CorePromiseClient.prototype.mainOutboundsInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/MainOutboundsInfo',
      request,
      metadata || {},
      methodDescriptor_Core_MainOutboundsInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.SystemInfo>}
 */
const methodDescriptor_Core_GetSystemInfo = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/GetSystemInfo',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.sdmrpc.SystemInfo,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.SystemInfo.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.SystemInfo>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.getSystemInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/GetSystemInfo',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemInfo);
};


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.SystemInfo>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CorePromiseClient.prototype.getSystemInfo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/GetSystemInfo',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemInfo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.SetupRequest,
 *   !proto.sdmrpc.Response>}
 */
const methodDescriptor_Core_Setup = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/Setup',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.SetupRequest,
  proto.sdmrpc.Response,
  /**
   * @param {!proto.sdmrpc.SetupRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.Response.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.SetupRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.setup =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/Setup',
      request,
      metadata || {},
      methodDescriptor_Core_Setup,
      callback);
};


/**
 * @param {!proto.sdmrpc.SetupRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.Response>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.setup =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/Setup',
      request,
      metadata || {},
      methodDescriptor_Core_Setup);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.ParseRequest,
 *   !proto.sdmrpc.ParseResponse>}
 */
const methodDescriptor_Core_Parse = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/Parse',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.ParseRequest,
  proto.sdmrpc.ParseResponse,
  /**
   * @param {!proto.sdmrpc.ParseRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.ParseResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.ParseRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.ParseResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.ParseResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.parse =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/Parse',
      request,
      metadata || {},
      methodDescriptor_Core_Parse,
      callback);
};


/**
 * @param {!proto.sdmrpc.ParseRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.ParseResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.parse =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/Parse',
      request,
      metadata || {},
      methodDescriptor_Core_Parse);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.ChangeSdmSettingsRequest,
 *   !proto.sdmrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_ChangeSdmSettings = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/ChangeSdmSettings',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.ChangeSdmSettingsRequest,
  proto.sdmrpc.CoreInfoResponse,
  /**
   * @param {!proto.sdmrpc.ChangeSdmSettingsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.ChangeSdmSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.changeSdmSettings =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/ChangeSdmSettings',
      request,
      metadata || {},
      methodDescriptor_Core_ChangeSdmSettings,
      callback);
};


/**
 * @param {!proto.sdmrpc.ChangeSdmSettingsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.changeSdmSettings =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/ChangeSdmSettings',
      request,
      metadata || {},
      methodDescriptor_Core_ChangeSdmSettings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.StartRequest,
 *   !proto.sdmrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_StartService = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/StartService',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.StartRequest,
  proto.sdmrpc.CoreInfoResponse,
  /**
   * @param {!proto.sdmrpc.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.startService =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/StartService',
      request,
      metadata || {},
      methodDescriptor_Core_StartService,
      callback);
};


/**
 * @param {!proto.sdmrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.startService =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/StartService',
      request,
      metadata || {},
      methodDescriptor_Core_StartService);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_Stop = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/Stop',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.sdmrpc.CoreInfoResponse,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.stop =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/Stop',
      request,
      metadata || {},
      methodDescriptor_Core_Stop,
      callback);
};


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.stop =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/Stop',
      request,
      metadata || {},
      methodDescriptor_Core_Stop);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.StartRequest,
 *   !proto.sdmrpc.CoreInfoResponse>}
 */
const methodDescriptor_Core_Restart = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/Restart',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.StartRequest,
  proto.sdmrpc.CoreInfoResponse,
  /**
   * @param {!proto.sdmrpc.StartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.CoreInfoResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.CoreInfoResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.CoreInfoResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.restart =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/Restart',
      request,
      metadata || {},
      methodDescriptor_Core_Restart,
      callback);
};


/**
 * @param {!proto.sdmrpc.StartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.CoreInfoResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.restart =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/Restart',
      request,
      metadata || {},
      methodDescriptor_Core_Restart);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.SelectOutboundRequest,
 *   !proto.sdmrpc.Response>}
 */
const methodDescriptor_Core_SelectOutbound = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/SelectOutbound',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.SelectOutboundRequest,
  proto.sdmrpc.Response,
  /**
   * @param {!proto.sdmrpc.SelectOutboundRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.Response.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.SelectOutboundRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.selectOutbound =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/SelectOutbound',
      request,
      metadata || {},
      methodDescriptor_Core_SelectOutbound,
      callback);
};


/**
 * @param {!proto.sdmrpc.SelectOutboundRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.Response>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.selectOutbound =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/SelectOutbound',
      request,
      metadata || {},
      methodDescriptor_Core_SelectOutbound);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.UrlTestRequest,
 *   !proto.sdmrpc.Response>}
 */
const methodDescriptor_Core_UrlTest = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/UrlTest',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.UrlTestRequest,
  proto.sdmrpc.Response,
  /**
   * @param {!proto.sdmrpc.UrlTestRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.Response.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.UrlTestRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.urlTest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/UrlTest',
      request,
      metadata || {},
      methodDescriptor_Core_UrlTest,
      callback);
};


/**
 * @param {!proto.sdmrpc.UrlTestRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.Response>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.urlTest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/UrlTest',
      request,
      metadata || {},
      methodDescriptor_Core_UrlTest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.GenerateWarpConfigRequest,
 *   !proto.sdmrpc.WarpGenerationResponse>}
 */
const methodDescriptor_Core_GenerateWarpConfig = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/GenerateWarpConfig',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.GenerateWarpConfigRequest,
  proto.sdmrpc.WarpGenerationResponse,
  /**
   * @param {!proto.sdmrpc.GenerateWarpConfigRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.WarpGenerationResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.GenerateWarpConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.WarpGenerationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.WarpGenerationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.generateWarpConfig =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/GenerateWarpConfig',
      request,
      metadata || {},
      methodDescriptor_Core_GenerateWarpConfig,
      callback);
};


/**
 * @param {!proto.sdmrpc.GenerateWarpConfigRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.WarpGenerationResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.generateWarpConfig =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/GenerateWarpConfig',
      request,
      metadata || {},
      methodDescriptor_Core_GenerateWarpConfig);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.SystemProxyStatus>}
 */
const methodDescriptor_Core_GetSystemProxyStatus = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/GetSystemProxyStatus',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.sdmrpc.SystemProxyStatus,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.SystemProxyStatus.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.SystemProxyStatus)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.SystemProxyStatus>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.getSystemProxyStatus =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/GetSystemProxyStatus',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemProxyStatus,
      callback);
};


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.SystemProxyStatus>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.getSystemProxyStatus =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/GetSystemProxyStatus',
      request,
      metadata || {},
      methodDescriptor_Core_GetSystemProxyStatus);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.SetSystemProxyEnabledRequest,
 *   !proto.sdmrpc.Response>}
 */
const methodDescriptor_Core_SetSystemProxyEnabled = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/SetSystemProxyEnabled',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.SetSystemProxyEnabledRequest,
  proto.sdmrpc.Response,
  /**
   * @param {!proto.sdmrpc.SetSystemProxyEnabledRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.Response.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.SetSystemProxyEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.setSystemProxyEnabled =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.Core/SetSystemProxyEnabled',
      request,
      metadata || {},
      methodDescriptor_Core_SetSystemProxyEnabled,
      callback);
};


/**
 * @param {!proto.sdmrpc.SetSystemProxyEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.Response>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.CorePromiseClient.prototype.setSystemProxyEnabled =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.Core/SetSystemProxyEnabled',
      request,
      metadata || {},
      methodDescriptor_Core_SetSystemProxyEnabled);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.LogMessage>}
 */
const methodDescriptor_Core_LogListener = new grpc.web.MethodDescriptor(
  '/sdmrpc.Core/LogListener',
  grpc.web.MethodType.SERVER_STREAMING,
  base_pb.Empty,
  proto.sdmrpc.LogMessage,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.LogMessage.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.LogMessage>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CoreClient.prototype.logListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/LogListener',
      request,
      metadata || {},
      methodDescriptor_Core_LogListener);
};


/**
 * @param {!proto.sdmrpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.LogMessage>}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.CorePromiseClient.prototype.logListener =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/sdmrpc.Core/LogListener',
      request,
      metadata || {},
      methodDescriptor_Core_LogListener);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sdmrpc.TunnelServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.sdmrpc.TunnelServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.TunnelStartRequest,
 *   !proto.sdmrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Start = new grpc.web.MethodDescriptor(
  '/sdmrpc.TunnelService/Start',
  grpc.web.MethodType.UNARY,
  proto.sdmrpc.TunnelStartRequest,
  proto.sdmrpc.TunnelResponse,
  /**
   * @param {!proto.sdmrpc.TunnelStartRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.TunnelResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.TunnelStartRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.TunnelServiceClient.prototype.start =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.TunnelService/Start',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Start,
      callback);
};


/**
 * @param {!proto.sdmrpc.TunnelStartRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.TunnelServicePromiseClient.prototype.start =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.TunnelService/Start',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Start);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Stop = new grpc.web.MethodDescriptor(
  '/sdmrpc.TunnelService/Stop',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.sdmrpc.TunnelResponse,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.TunnelResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.TunnelServiceClient.prototype.stop =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.TunnelService/Stop',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Stop,
      callback);
};


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.TunnelServicePromiseClient.prototype.stop =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.TunnelService/Stop',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Stop);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Status = new grpc.web.MethodDescriptor(
  '/sdmrpc.TunnelService/Status',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.sdmrpc.TunnelResponse,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.TunnelResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.TunnelServiceClient.prototype.status =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.TunnelService/Status',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Status,
      callback);
};


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.TunnelServicePromiseClient.prototype.status =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.TunnelService/Status',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Status);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.sdmrpc.Empty,
 *   !proto.sdmrpc.TunnelResponse>}
 */
const methodDescriptor_TunnelService_Exit = new grpc.web.MethodDescriptor(
  '/sdmrpc.TunnelService/Exit',
  grpc.web.MethodType.UNARY,
  base_pb.Empty,
  proto.sdmrpc.TunnelResponse,
  /**
   * @param {!proto.sdmrpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.sdmrpc.TunnelResponse.deserializeBinary
);


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.sdmrpc.TunnelResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.sdmrpc.TunnelResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.sdmrpc.TunnelServiceClient.prototype.exit =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/sdmrpc.TunnelService/Exit',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Exit,
      callback);
};


/**
 * @param {!proto.sdmrpc.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.sdmrpc.TunnelResponse>}
 *     Promise that resolves to the response
 */
proto.sdmrpc.TunnelServicePromiseClient.prototype.exit =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/sdmrpc.TunnelService/Exit',
      request,
      metadata || {},
      methodDescriptor_TunnelService_Exit);
};


module.exports = proto.sdmrpc;

