// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: v2/accountcrypto/account_crypto.proto

package accountcrypto

import (
	context "context"
	hcommon "github.com/HZ-PRE/kuailei-core/v2/hcommon"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountCrypto_GetAppAesKey_FullMethodName = "/accountcrypto.AccountCrypto/GetAppAesKey"
)

// AccountCryptoClient is the client API for AccountCrypto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Only exposed on the authenticated, pinned-TLS local core RPC server.
type AccountCryptoClient interface {
	GetAppAesKey(ctx context.Context, in *hcommon.Empty, opts ...grpc.CallOption) (*hcommon.Response, error)
}

type accountCryptoClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountCryptoClient(cc grpc.ClientConnInterface) AccountCryptoClient {
	return &accountCryptoClient{cc}
}

func (c *accountCryptoClient) GetAppAesKey(ctx context.Context, in *hcommon.Empty, opts ...grpc.CallOption) (*hcommon.Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(hcommon.Response)
	err := c.cc.Invoke(ctx, AccountCrypto_GetAppAesKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountCryptoServer is the server API for AccountCrypto service.
// All implementations must embed UnimplementedAccountCryptoServer
// for forward compatibility.
//
// Only exposed on the authenticated, pinned-TLS local core RPC server.
type AccountCryptoServer interface {
	GetAppAesKey(context.Context, *hcommon.Empty) (*hcommon.Response, error)
	mustEmbedUnimplementedAccountCryptoServer()
}

// UnimplementedAccountCryptoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountCryptoServer struct{}

func (UnimplementedAccountCryptoServer) GetAppAesKey(context.Context, *hcommon.Empty) (*hcommon.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppAesKey not implemented")
}
func (UnimplementedAccountCryptoServer) mustEmbedUnimplementedAccountCryptoServer() {}
func (UnimplementedAccountCryptoServer) testEmbeddedByValue()                       {}

// UnsafeAccountCryptoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountCryptoServer will
// result in compilation errors.
type UnsafeAccountCryptoServer interface {
	mustEmbedUnimplementedAccountCryptoServer()
}

func RegisterAccountCryptoServer(s grpc.ServiceRegistrar, srv AccountCryptoServer) {
	// If the following call pancis, it indicates UnimplementedAccountCryptoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountCrypto_ServiceDesc, srv)
}

func _AccountCrypto_GetAppAesKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hcommon.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountCryptoServer).GetAppAesKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountCrypto_GetAppAesKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountCryptoServer).GetAppAesKey(ctx, req.(*hcommon.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountCrypto_ServiceDesc is the grpc.ServiceDesc for AccountCrypto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountCrypto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accountcrypto.AccountCrypto",
	HandlerType: (*AccountCryptoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppAesKey",
			Handler:    _AccountCrypto_GetAppAesKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v2/accountcrypto/account_crypto.proto",
}
